export const BID_INCREMENT_CENTS = 5_000;
export const BID_INCREMENT_DOLLARS = BID_INCREMENT_CENTS / 100;
export const COLOR_BORDER_ADDON_CENTS = 1_000;
export const COLOR_BORDER_ADDON_DOLLARS = COLOR_BORDER_ADDON_CENTS / 100;
